name: lucky7-scrape

on:
  schedule:
    - cron: "*/20 * * * *"   # every 20 min
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 55

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4

      - name: Prepare folders
        run: mkdir -p debug

      - name: Run scraper (Xvfb)
        env:
          NOH_USER: ${{ secrets.NOH_USER }}
          NOH_PASS: ${{ secrets.NOH_PASS }}
          LUCKY7_URL: ${{ secrets.LUCKY7_URL }}   # put your site home URL in repo secrets
          CSV_PATH: lucky7_data.csv
          RUN_SECONDS: 3000            # ~50 min budget per run
          MAX_ROUNDS: "0"              # unlimited within time cap
          GAME_PREF: "LUCKY 7"         # prefer Lucky 7; Hi-Low fallback
          MAX_TABLES: "10"             # rotate more tables if stuck
          ROUND_TIMEOUT: "120"         # give one round some time to settle
          DEBUG_DUMP: "1"
          PYTHONUNBUFFERED: "1"
        run: |
          xvfb-run -a -s "-screen 0 1600x900x24" python -u scraper.py

      - name: Show outputs (tree + CSV head)
        if: always()
        run: |
          echo "Workspace tree:"; ls -lah
          echo "CSV preview:"
          if [ -f lucky7_data.csv ]; then
            echo "lines:"; wc -l lucky7_data.csv
            head -n 20 lucky7_data.csv
          else
            echo "CSV missing"
          fi
          echo "Debug tree:"; ls -lah debug || true

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lucky7-data
          path: lucky7_data.csv
          if-no-files-found: warn

      - name: Upload debug bundle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-snapshots
          path: debug/
          if-no-files-found: warn
